name: simuk-dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python >= 3.11
  - pip
  - python >= 3.11
  - pymc>=5.20.1
  - bambi>=0.15.0
  - arviz>=0.20.0
  - black=22.3.0
  - click=8.0.4
  - pytest-cov>=2.6.1
  - pytest>=4.4.0
  - pre-commit>=2.19
  - ruff==0.9.1

